Ikabot-Collective/ikabot

ikabot/command_line.py, ikabot/config.py, ikabot/funcion/alertarAtaques.py, ikabot/funcion/alertarPocoVino.py, ikabot/funcion/botDonador.py, ikabot/funcion/buscarEspacios.py, ikabot/funcion/entrarDiariamente.py, ikabot/funcion/enviarVino.py, ikabot/funcion/menuRutaComercial.py, ikabot/funcion/subirEdificio.py, ikabot/helpers/botComm.py, ikabot/helpers/getJson.py, ikabot/helpers/signals.py, ikabot/web/sesion.py
- Reescribo subirEdifiico
- Agrego output de debug en varias funciones
- Muevo los archivos de cookie y telegram al home directory del usuario
- Varios bug fix
=> Subir edificio bug

README.md, ikabot/command_line.py, ikabot/funcion/comprarRecursos.py, ikabot/funcion/enviarVino.py, ikabot/funcion/subirEdificio.py, ikabot/helpers/getJson.py, ikabot/helpers/pedirInfo.py, ikabot/helpers/planearViajes.py
- Agrego funcionalidad de compra de recursos en la Tienda
- Arreglos menosres:
- mejoro funcion read -> borra la linea de la terminal de mejor manera
- agrego opciones de Y/N a varios read
- quito uso de funcion gerBarcosTotales de PlanearViajes, no se usaba
=> Comprar recursos

README.md, ikabot/command_line.py, ikabot/funcion/distributeResourcesEvenly.py, ikabot/locale/en/LC_MESSAGES/command_line.po, setup.py
I have added the even distribution of resources feature to ikabot. The code is very well documented, and follows similar logic to the one that the non-even distribution feature uses. It's been tested 2 times and seems to be working fine. 
The usage of this feature is self explanatory as all one needs to do is provide a resource type and confirm the distribution execution.
For any further inquires I can be contacted via:
email: loco.bott@gmail.com
discord: locobott#1190
=> Even distribution of resources feature

.github/workflows/build.yml, ikabot/helpers/pedirInfo.py, ikabot/helpers/planRoutes.py, tests/function/test_distributeResources.py
First unit test here! Let's start with something easy :slightly_smiling_face:
=> Added test for distribute_evenly

ikabot/command_line.py, ikabot/function/autoPirate.py
Thanks to @ikagod for this _great_ feature
=> added autoPirate feature

README.md, ikabot/command_line.py, ikabot/function/investigate.py, ikabot/function/searchForIslandSpaces.py
Add the possibility to investigate from ikabot
=> Investigate

ikabot/helpers/botComm.py, ikabot/web/session.py
This pull request will hopefully solve #71.
I have tested this code once, and it worked fine. I hope it can be tested more in the future seeing as I have trouble getting this captcha presented to me. Future updates for this feature may include the ability for an automatic captcha resolution.
=> Lobby captcha solution

ikabot/function/constructionList.py
Hi physics spycat here,
I found that the issue with the construction list is in the image name to get the resource type, now the images are in a CDN without the name of the resource so I had to change this to fix texts.
I have tested to get this images from different countries and is always the same URL.
=> constructionList Update

ikabot/helpers/planRoutes.py
The api changed in some funny ways
- Cities that have no resource of some type can't have it zeroed anymore in the request
- Fixed some bugs that were quiet before for some reason.
- Since the bot must get the origin city to see the resources that are available, this is slightly slower.
- The request payload changed a little too.
Issue #108
=> Fix for the distribute resource

.github/workflows/build.yml
- Update python versions
- Update run command
=> Fix build github actions

README.md, ikabot/command_line.py, ikabot/function/dumpWorld.py, ikabot/helpers/gui.py
This feature lets the user create a data dump about all islands in the world server. The dumps are gzipped and can be searched through using this same feature.
=> Add feature to dump world

ikabot/function/alertAttacks.py
Does the error handling inside the while loop to make this feature more resillient to silent crashes
Currently if some error happens the function will quit, it should alert the user and wait to check for attacks again later.
Eg.: checking for attacks while ikariam does the backup might crash the function, it should just continue later, not quit
=> Error handling inside alertAttacks 'do_it' to not quit the function

.github/workflows/build_artifacts.yml, .github/workflows/release.yml
=> Setup new release workflow

.github/release.yml
=> add configuration for release

.gitignore, ikabot/function/activateMiracle.py, ikabot/function/buyResources.py, ikabot/function/getStatus.py, ikabot/web/session.py
=> fix wine offers, permanent values for miracles and population delegation

ikabot/function/autoPirate.py
Added optional mission schedule for autoPirate based on the time of day. Default values (stated in the process) are applied if no input has been made. Also added Telegram notification for 2 different Exceptions in the autoPirate function as they were missing.
=> autoPirate mission schedule based on time of day

ikabot/function/donationBot.py
Added 2 new donation methods, percentage of the current production rate and specific amount. Also added an option to split the donation amount to both types simultaneously. Fixed a small typo in a print while at it.
=> 2 new donation methods and dual option

ikabot/function/sellResources.py
=> Update sellResources function

ikabot/function/sellResources.py
Fixed issue in the buyResources function which was caused by the latest game update. Fix was made for sellResources function in PR #151 and this is an implementation of that fix into the other function with the same issue. 
TL;DR: This PR **_and_** PR #151 fixes the issue #149
=> Update buyResources function

ikabot/command_line.py, ikabot/config.py, ikabot/function/dumpWorld.py, ikabot/function/logs.py, ikabot/helpers/aesCipher.py, ikabot/helpers/botComm.py, ikabot/helpers/gui.py, ikabot/helpers/varios.py, ikabot/web/session.py
Added a full new logging system with four different log levels differing in severity: DEBUG, INFO, WARN and ERROR with WARN being the default log level.
- New session.writeLog function that can be used project-wide to write structured logs to disk
- Added ability to append last 5 requests to log entry
- Added ability to append traceback to the log entry
- Added new log viewing system
- Added ability to upload logs to pastebin
Currently logs are only created for some important events during the login process, and every time a message is sent or attempted to be sent to a Telegram bot. 
Contributors are welcome to use this new system in their modules or to update existing modules in order to make them more debuggable and troubleshootable.
=> Improve logging

ikabot/command_line.py, ikabot/function/autoPirate.py, ikabot/function/loginDaily.py, ikabot/function/logs.py, ikabot/function/searchForIslandSpaces.py, ikabot/helpers/planRoutes.py, ikabot/helpers/process.py, ikabot/helpers/varios.py, ikabot/web/session.py
This new feature allows a module to report it's own status back to the main menu where it is visible among other information about tasks in the running tasks table.
In this pull request the system has been fully implemented, and has been applied to the following modules:
- autoPirate now reports how many capture runs it has left until it exits and it also reports in the case that it is working on solving a captcha
- loginDaily now reports the last time it logged in
- any module that makes use of planRoutes will now report how many resources it still needs to send and where, this includes sendResources, distributeResources, constructBuilding and constructionList
- checkForIslandSpaces will now report which islands it is supposed to be checking and when the last check was performed.
Other …
=> Add task status

ikabot/function/getStatus.py
Simple adjustments and resolution of problem #140 , as well as improvements suggested by @johnvittu.
=> Fix housing space and citizen display

ikabot/function/getStatus.py, ikabot/function/stationArmy.py
Simple adjustments and resolution of problem #166!
=> Fix display of troop and ship numbers

ikabot/helpers/getJson.py, ikabot/helpers/pedirInfo.py
=> Update for ChooseCity and getIslands functions

ikabot/function/distributeResources.py
Finding cities mining this resource was not possible as the checking function compared different types.
=> fix distributing resources from mining cities

ikabot/function/trainArmy.py
This pull request introduces a significant enhancement, allowing users to have the flexibility to train or repeat training in all cities. This improvement enhances the overall user experience by providing greater control and convenience when managing troops and ships across various locations.
This pull request addresses the request from issue #87.
=> UpTrainArmy - Option to train or repeat training in all cities

ikabot/helpers/getJson.py, ikabot/helpers/pedirInfo.py, ikabot/helpers/varios.py
I had problems because some of my cities are in UTF-8, and were not readable on some menues. This is the fix that I thought of and it looks like has done the job so far.
=> Fix city names encoding

ikabot/command_line.py, ikabot/function/testTelegramBot.py
There shuld be a way to test if the telegram is working as expected
=> Add sending test message to telegram bot

ikabot/command_line.py, ikabot/function/autoPirate.py, ikabot/function/decaptchaConf.py, ikabot/function/killTasks.py, ikabot/function/update.py, ikabot/helpers/process.py, ikabot/web/session.py
To solve the issue with the process duplication I've added a manager class, which stores processes in it in dictionary by pid - to remove the duplicates. It's still saved in list in the session data.
Resolves #174
=> Add process list manager class

ikabot/command_line.py, ikabot/function/autoPirate.py, ikabot/function/decaptchaConf.py, ikabot/function/killTasks.py, ikabot/function/update.py, ikabot/helpers/process.py, ikabot/web/session.py
Reverts physics-sec/ikabot#202
=> Revert "Add process list manager class"

ikabot/helpers/botComm.py
In this PR I am attempting to rework the way Telegram data is input and validated. The old way used to be very confusing to people so I think this new approach will be more straightforward and intuitive. The process is as follows:
1. User is prompted to create a bot on Telegram by talking to @ botfather, and to obtain their newly-created bot's token
2. User is prompted to enter the token
3. A random 4 digit code is generated, and the user is prompted to send the command /ikabot [code] to their bot on Telegram.
4. Once the user presses enter, Ikabot checks for new messages on Telegram, if the command is found among new messages, the user's Telegram user ID is saved to session data and a confirmation message is sent over Telegram
No setting of Telegram username or talking to the bot prior …
=> Rework the way Telegram data is input

ikabot/function/autoPirate.py
Seems like the request changed since this function was written.
It is POST request now with 2 more parameters - "actionRequest" and "ajax"
=> Bugfix for autoconvert crew strength

ikabot/function/activateMiracle.py, ikabot/function/donationBot.py
Added status updates for activateMiracle and donationBot functions.
=> Add status updates

.github/workflows/release.yml, ikabot/config.py, ikabot/function/webServer.py, ikabot/helpers/gui.py, setup.py
- Fix change version in release.yml
- Change version constant name
- Format files with Black formatter
✅ Pipeline tested on my fork
Should fix #250
=> Fix #250 : auto change version in release pipeline

ikabot/function/donationBot.py
Fix syntax warning in the donationBot function
=> Syntax fix for donationBot function

ikabot/function/investigate.py
Added 3rd option for investigation, automatic experiment conduction. Instead of setting a fixed amount of experiments to conduct based on the available resources, this adds an option to check the selected town every 4 hours and conduct an experiment if there are enough resources.
**Added a cooldown check before trying to conduct an experiment.**
_This fixes a bug in the function which caused a false conduction._ 
Switched most Telegram notifications to status updates.
=> [Investigate] Add loop option, bugfix, add status updates

ikabot/function/dumpWorld.py, ikabot/helpers/gui.py
2 new searching options in dumpworld
1) search by alliance tag. It prints all players of that alliance along with the coordinates for all of their cities.
2) search for a specific island by coordinates. It prints almost all data about the island contained in the deep scan. See pictures below.
=> Upgraded searching tools for deep scanned islands

ikabot/function/constructionList.py, ikabot/function/distributeResources.py, ikabot/function/sendResources.py, ikabot/helpers/naval.py, ikabot/helpers/planRoutes.py
New option for all (?) transportation functions to use freighters instead of trade ships. Does not interfere with existing transport functions, since the freighters option is set to false by default if there's no variable stating otherwise.
I wrote this a little while ago, just havent made a PR out of it until suggestion #265.
=> Option to use freighters for transports

ikabot/config.py, ikabot/function/webServer.py
Option for selecting a custom port for the web server to use, really useful for consistency.
=> Custom web server port

ikabot/helpers/varios.py, ikabot/web/session.py
add last login Date (Year-Month-Day)
fixes #267 (vacation mode info is not presend in Lobby Data(Accounts) or i could not find it)
=> add Last Login Date

ikabot/command_line.py, ikabot/function/activateMiracle.py, ikabot/function/attackBarbarians.py, ikabot/function/autoBarbarians.py
This pull request aims to introduce a new feature to Ikabot: the Auto Barbarian. Its primary focus is to enable players to farm resources provided by the barbarians (4M resources from levels 1 to 49).
- Added functionality to `obtainMiraclesAvailable` to extract the activation level of miracles (as displayed in the temple);
- Added a barbarian grind selection option in the settings menu;
- Fixed an issue in `get_unit_data` where the speed regex relied on a text that could be subject to translation;
- Enhanced the `get_unit_data` function to also extract unit names;
- Added the `autoBarbarians` module and its functionalities.
Personally, I've always enjoyed attacking barbarians, but I found the existing module somewhat lacking in utility. Based on this, I had the idea to combine what I …
=> Added auto (grind) attack function to barbarians

ikabot/function/buyResources.py
Resource types detected properly.
=> Fix Resource Type Detection in buyResources.py

ikabot/function/buyResources.py
=> Fix Offer Detection in buyResources.py

ikabot/function/constructionList.py
In Ikariam [v12.1.0] the exact amount of resources is displayed in the tooltip
=> Fix constructionList costs calculation

ikabot/function/constructionList.py
This update allow to to propperly get all values from the construction list by removing blank spaces
=> Construction List update

ikabot/function/sellResources.py
Update of Sell Resources function to make it work with Ikariam v12.1.0
=> Fix HTML parsing in Sell Resources function

ikabot/command_line.py, ikabot/config.py, ikabot/function/consolidateResources.py
Related to https://github.com/Ikabot-Collective/ikabot/issues/271
Added new function "Consolidate resources" which allows to gather specified resources to specified city up to a limit every x hours
https://github.com/user-attachments/assets/fff8952e-c4ad-4e09-94b3-ab90be02d043
=> Consolidate resources to specified city

ikabot/helpers/pedirInfo.py
Hello gang, I have started investigating why my ikabot instances crash so often. This change will fix the infinite recursion stack overflow when inputs into the read function are invalid and not resolved by by the ascii escape. I have added more input validation checks and a max_retries value to the recursion to return None after 20 tries (adjust as you see fit).
```shell
File "/root/.local/lib/python3.11/site-packages/ikabot/helpers/pedirInfo.py", line 65, in read
File "/root/.local/lib/python3.11/site-packages/ikabot/helpers/pedirInfo.py", line 60, in _invalid
File "/root/.local/lib/python3.11/site-packages/ikabot/helpers/pedirInfo.py", line 65, in read
File "/root/.local/lib/python3.11/site-packages/ikabot/helpers/pedirInfo.py", line 60, in _invalid
File …
```
=> fixed infinite recursion stack overflow in read()

ikabot/function/alertLowWine.py, ikabot/function/donationBot.py, ikabot/helpers/resources.py
Changed the getProductionPerSecond logic to ...PerMinute as it's fetched from Ikariam. Fixes donationBot's option 2 and replaced the helper function's name in alertLowWine. 
Pardon me for disappearing for a year and then destroying the repo out of nowhere xD I haven't got a second for any freetime projects due to a lot of work IRL.
=> Fix getProduction helper
